### ISSUE TITLE
Support `phpoffice/phpspreadsheet` v2

### ISSUE THREAD

**Issue by mvhirsch** [codeinchq/symfony-phpspreadsheet-response#4]
v2 is straight forward. It just removed some deprecations. This code seems not to use deprecated methods.

https://github.com/PHPOffice/PhpSpreadsheet/blob/master/CHANGELOG.md#200---2024-01-04

**Comment by joanfabregat** [comment]
Thanks. I'll be looking into that.

**Comment by joanfabregat** [comment]
It’s fixed! The library is now compatible with both the v1 and v2 branches.

**Comment by mvhirsch** [comment]
Thank you!
